### PR TITLE
test: add unit test to catch missing distribution to subsystems faster

### LINKED ISSUE #2486: Network Bridge: test that received messages are forwarded to the appropriate subsystem
63de90a091df7a1 shows that the way we do this forwarding is fairly error-prone in the addition of new subsystems. We should have unit tests for all of these.

Furthermore, it would be nice to have a way for the test or compilation to fail when new `ValidationProtocol` or `CollationProtocol` variants are added. An exhaustive match somewhere would help with that.

### PR DESCRIPTION
**Pull request by drahnr**
Adds a small unit test to assure early compilation failure.

TODO

* [x] ~attempt to use the type system to guarantee error variants~ does not work due to the 1:N mapping
* [x] implement a unit test to be able to verify correctness
* [x] create a small proc-macro to automate the code for dispatching
* [x] improve proc-macro error handling 

Closes #2486

### CODE REVIEW

File: node/network/bridge/src/lib.rs [hunk 1]
```diff
@@ -1536,4 +1544,32 @@ mod tests {
...
+				AllMessages::RuntimeApi(_) => unreachable!("Not interested in network events"),
+				AllMessages::AvailabilityStore(_) => unreachable!("Not interested in network events"),
+				AllMessages::NetworkBridge(_) => unreachable!("Not interested in network events"),
+				AllMessages::CollationGeneration(_) => unreachable!("Not interested in network events"),
+				AllMessages::ApprovalVoting(_) => unreachable!("Not interested in network events"),
+				AllMessages::ApprovalDistribution(_) => {}
+				// add new variants as needed
+			}
+		}
+	}
```
Comment (ordian) [inline node/network/bridge/src/lib.rs:1574]: how is it going to make sure we didn't forget about a message? my understanding is that it will only panic if we accidentally forwarded a wrong message type, but not if we forgot about the right one?

Comment (drahnr) [reply node/network/bridge/src/lib.rs:1574]: That part requires a counter, but I wanted to first see if that can be remedied by a procmacro.

If one forgets to add a message here, it won't even compile, and the unit test calls exactly one `fn`.

Comment (ordian) [reply node/network/bridge/src/lib.rs:1574]: well, you can add it here, but not in `spread_event_to_subsystems` (`multiply_message`) and it will compile :P

Comment (ordian) [reply node/network/bridge/src/lib.rs:1574]: yeah, counter sounds workable, like https://github.com/paritytech/polkadot/blob/0658b3d2dce54d497d394419f046df198ce2b939/node/overseer/src/lib.rs#L2772

**Review by ordian — APPROVED** [review]
Looks good once it compiles.
cc #2480

**Comment by drahnr** [comment]
Mockup for a procmacro dealing with this better (annotation and generated `fn`). The idea is having to have an explicit opt out with `#[consumer(skip)]` which, if not done consistently will cause compile errors rather than opt in which could silently work.
:bike: :house: appreciated.

```

	struct NetEvent {
		data: u8,
	}

	#[good_news_everyone_inner(NetEvent)]
	enum Inner1 {
		Msg1,
		Msg2(NetEvent),
	}



	#[good_news_everyone_inner(NetEvent)]
	enum Inner2 {
		No,
		Msg7(NetEvent),
	}

	#[good_news_everyone(NetEvent)]
	enum AllMessages {
		Sub1(Inner1),
		Sub2(Inner2),

		#[consumer(skip)]
		Sub3,

		#[consumer(skip)]
		Sub4(Inner2),
	}


	// generated:
	fn spread(event: NetEvent) -> impl Iterator<Item=AllMessages> {
		vec![
			AllMessages::Sub1(Inner1::from(event.clone())),
			AllMessages::Sub2(Inner2::from(event.clone())),
		].into_iter()
	}
```

**Comment by drahnr** [comment]
Includes an initial impl of a proc-macro that generates

```
impl AllMessages {
  pub fn dispatch_iter(event: X) -> impl Iterator<Item=Self> + Send {
  ...
  }
}
```
where `X` is a concrete type.

All `enum AllMessages`  variants are checked if they are annotated with `#[skip]`, if so they are not included in the `fn dispatch_iter()` logic.

All others are attempted.

Safety emerges from 3 ends:
* unit test covers the generated code
* explicit opt-out with `#[skip]` rather than opt-in
* accidentally forgetting a skip either ends up in
  * an additional messages being sent to a subsystem
  * compilation error due to the lack of a `From::from` implementation for the `X` (see above)

**Comment by drahnr** [comment]
:bike: :house: -ing appreciated :upside_down_face:

**Review by eskimor — APPROVED** [review]

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 2]
```diff
@@ -0,0 +1,191 @@
...
+				.filter(|field| {
+					if let Some(ident) = &field.ident {
+						ident.to_string() == "inner".to_owned()
+					} else {
+						false
+					}
+				})
+				.map(|field| Some(field.ty.clone()))
+				.next()
+				.unwrap(),
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:94]: Never unwrap in macro code.

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+				.iter()
+				.filter(|field| {
+					if let Some(ident) = &field.ident {
+						ident.to_string() == "inner".to_owned()
+					} else {
+						false
+					}
+				})
+				.map(|field| Some(field.ty.clone()))
+				.next()
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:93]: find_map is what you want here.

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+			Fields::Unnamed(FieldsUnnamed { paren_token: _, unnamed }) if !skip => unnamed
+				.first()
+				.map(|field| Some(field.ty.clone())).unwrap(),
+				// .ok_or_else(|| input.error("Must at least have one inner type or be skipped"))?,
+			_ if skip => None,
+			_ => {
+				// return Err(
+				// 	input.error("Enum variant has either not skip and doesn't match anything, or somethin worse")
+				// )
+				unreachable!("fooo")
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:107]: Nope

**Review by bkchr — CHANGES_REQUESTED** [review]

File: node/subsystem/dispatch-gen/src/lib.rs (hunk 4 above)
Comment (drahnr) [reply node/subsystem/dispatch-gen/src/lib.rs:107]: Did you see the unchecked TODO in the issue description? 🙃

Comment (bkchr) [reply node/subsystem/dispatch-gen/src/lib.rs:107]: I just wanted to be sure :D

**Comment by drahnr** [comment]
While there could be more time invested to generalize this further, factually this serves the purpose and is sufficiently clean

File: node/network/bridge/src/lib.rs [hunk 5]
```diff
@@ -1546,4 +1519,39 @@ mod tests {
...
+		for msg in AllMessages::dispatch_iter(NetworkBridgeEvent::PeerDisconnected(PeerId::random())) {
+			match msg {
+				AllMessages::CandidateValidation(_) => unreachable!("Not interested in network events"),
+				AllMessages::CandidateBacking(_) => unreachable!("Not interested in network events"),
+				AllMessages::CandidateSelection(_) => unreachable!("Not interested in network events"),
+				AllMessages::ChainApi(_) => unreachable!("Not interested in network events"),
+				AllMessages::CollatorProtocol(_) => unreachable!("Not interested in network events"),
+				AllMessages::StatementDistribution(_) => { cnt += 1; }
+				AllMessages::AvailabilityDistribution(_) => { cnt += 1; }
+				AllMessages::AvailabilityRecovery(_) => unreachable!("Not interested in network events"),
```
Comment (ordian) [inline node/network/bridge/src/lib.rs:1540]: https://github.com/paritytech/polkadot/pull/2480/commits/63de90a091df7a1b84a9ffecd1e10c25481e7131

File: node/network/bridge/src/lib.rs [hunk 6]
```diff
@@ -1546,4 +1519,39 @@ mod tests {
 			}
 		});
 	}
+
+
```
Comment (bkchr) [inline node/network/bridge/src/lib.rs:1523]:
```suggestion
```

File: node/subsystem/Cargo.toml [hunk 7]
```diff
@@ -23,6 +23,7 @@ polkadot-node-network-protocol = { path = "../network/protocol" }
 polkadot-primitives = { path = "../../primitives" }
 polkadot-statement-table = { path = "../../statement-table" }
 polkadot-node-jaeger = { path = "../jaeger" }
+polkadot-procmacro-subsystem-dispatch-gen = { path = "./dispatch-gen" }
```
Comment (bkchr) [inline node/subsystem/Cargo.toml:26]:
```suggestion
polkadot-procmacro-subsystem-dispatch-gen = { path = "dispatch-gen" }
```

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 8]
```diff
@@ -0,0 +1,216 @@
...
+use proc_macro2::TokenStream;
+use quote::{quote, ToTokens};
+use std::fmt;
+use syn::{parse2, Error, Fields, FieldsNamed, FieldsUnnamed, Ident, ItemEnum, Path, Result, Type, Variant};
+
+#[proc_macro_attribute]
+pub fn subsystem_dispatch_gen(attr: proc_macro::TokenStream, item: proc_macro::TokenStream) -> proc_macro::TokenStream {
+	let attr = proc_macro2::TokenStream::from(attr);
+	let item = proc_macro2::TokenStream::from(item);
+	proc_macro::TokenStream::from(subsystem_dispatch_gen2(attr, item))
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:26]: Can we please drop this random `2` postfix?

And you can just put the content of `subsystem_dispatch_gen2` into this function.

And you can also just call `into` instead of writing out the full type.

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 9]
```diff
@@ -0,0 +1,216 @@
...
+	fn to_tokens(&self, tokens: &mut proc_macro2::TokenStream) {
+		if let Some(inner) = &self.variant.inner {
+			let enum_name = &self.ty;
+			let variant_name = &self.variant.name;
+
+			let ts = quote! {
+				#enum_name::#variant_name(#inner::from(event))
+			};
+
+			tokens.extend(std::iter::once(ts));
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:54]:
```suggestion
			quote! {
				#enum_name::#variant_name(#inner::from(event))
			}.to_tokens(tokens);
```

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 10]
```diff
@@ -0,0 +1,216 @@
...
+		// look for one called inner
+		Fields::Named(FieldsNamed { brace_token: _, named }) if !skip => named
+			.iter()
+			.filter(
+				|field| {
+					if let Some(ident) = &field.ident {
+						ident.to_string() == "inner".to_owned()
+					} else {
+						false
+					}
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:91]:
```suggestion
					if let Some(ident) = &field.ident {
						ident == "inner"
					} else {
						false
					}
```

But can we not also just do `field.ident == Some("inner")`?

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 11]
```diff
@@ -0,0 +1,216 @@
...
+				span,
+				"Must be annotated with #[skip] or the first wrapped type must impl `From<_>`.",
+			))
+		}
+	};
+
+	Ok(EnumVariantDispatch { name: variant.ident, inner })
+}
+
+fn impl_subsystem_dispatch_gen2(attr: TokenStream, item: TokenStream) -> Result<proc_macro2::TokenStream> {
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:129]: Please drop the 2 ;)

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 12]
```diff
@@ -0,0 +1,216 @@
...
+
+	orig.extend(quote! {
+		impl #message_enum {
+			#[doc = #msg]
+			pub fn dispatch_iter(event: #event_ty) -> impl Iterator<Item=Self> + Send {
+
+				let mut iter = None.into_iter();
+
+				#(
+				let mut iter = iter.chain(std::iter::once(event.focus().ok().map(|event| {
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:155]:
```suggestion
					let mut iter = iter.chain(std::iter::once(event.focus().ok().map(|event| {
```

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 13]
```diff
@@ -0,0 +1,216 @@
...
+						#variants
+					})));
+
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:158]:
```suggestion
```

File: node/subsystem/dispatch-gen/Cargo.toml [hunk 14]
```diff
@@ -0,0 +1,18 @@
...
+description = "Small proc macro to create the distribution code for network events"
+
+[lib]
+proc-macro = true
+
+[dependencies]
+syn = { version = "1.0", features = ["full"] }
+quote = "1.0"
+proc-macro2 = "1.0"
+assert_matches = "1"
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/Cargo.toml:15]: Please always specify the full version, including the patch version.

File: node/subsystem/dispatch-gen/src/lib.rs [hunk 15]
```diff
@@ -0,0 +1,216 @@
...
+	let mut orig = ie.to_token_stream();
+
+	let msg = "Generated by #[subsystem_dispatch_gen] proc-macro.";
+
+	orig.extend(quote! {
+		impl #message_enum {
+			#[doc = #msg]
+			pub fn dispatch_iter(event: #event_ty) -> impl Iterator<Item=Self> + Send {
+
```
Comment (bkchr) [inline node/subsystem/dispatch-gen/src/lib.rs:151]:
```suggestion
```

**Review by bkchr — APPROVED** [review]
Some nitpicks, but otherside looks good.

File: node/network/bridge/src/lib.rs (hunk 5 above)
Comment (ordian) [reply node/network/bridge/src/lib.rs:1539]:
```suggestion
				AllMessages::AvailabilityRecovery(_) => { cnt += 1; }
```

File: node/network/bridge/src/lib.rs [hunk 16]
```diff
@@ -1546,4 +1519,38 @@ mod tests {
 			}
 		});
 	}
+
+	#[test]
+	fn spread_event_to_subsystems_is_up_to_date() {
+		// Number of subsystems expected to be interested in a network event,
+		// and hence the network event broadcasted to.
+		const EXPECTED_COUNT: usize = 5;
```
Comment (ordian) [inline node/network/bridge/src/lib.rs:1527]:
```suggestion
		const EXPECTED_COUNT: usize = 6;
```

File: node/subsystem/dispatch-gen/src/lib.rs (hunk 10 above)
Comment (drahnr) [reply node/subsystem/dispatch-gen/src/lib.rs]: Doesn't work, since `Option<Ident>` cannot be compared with `Option<&str>`

File: node/subsystem/dispatch-gen/src/lib.rs (hunk 11 above)
Comment (drahnr) [reply node/subsystem/dispatch-gen/src/lib.rs]: Soo, the `2` was added to distinguish between `proc_macro2` and `proc_macro` API types, renamed to `_inner`.

File: node/subsystem/dispatch-gen/src/lib.rs (hunk 8 above)
Comment (drahnr) [reply node/subsystem/dispatch-gen/src/lib.rs]: If I just make it all spaghetti, then I have to be more careful on the return type, so the indirection keeps the error handling cleanly out of there.

**Comment by drahnr** [comment]
bot merge

**Comment by drahnr** [comment]
bot merge
