### PR TITLE
Retry failed PVF prepare jobs

### LINKED ISSUE #4288: Allow retrying for rejected PVFs
In case the PVF validation host gets a precheck_pvf/execute_pvf request and it knows that preparation for that PVF is already failed, and a certain amount of time has passed since that attempt, the validation host should give that PVF another shot.

Naively, validation host should probably remember at which time it compiled the artifact in question. During the preparation request we won't bail unconditionally if the artifact is already in memory, but check if the cooldown period has passed and if so we try again.

### PR DESCRIPTION
**Pull request by m-cat**
# PULL REQUEST

## Overview

- Keep track of the time of failure and the number of failures.
- If we get a request to prepare a PVF, retry if:
  - Enough time has elapsed since a failure, and
  - The number of failures is not greater than `NUM_PREPARE_RETRIES`

### TODO

- [x] How to test this?

## Issues closed

Closes #4288

### CODE REVIEW

File: node/core/pvf/src/host.rs [hunk 1]
```diff
@@ -543,10 +595,29 @@ async fn handle_heads_up(
 				ArtifactState::Prepared { last_time_needed, .. } => {
 					*last_time_needed = now;
 				},
-				ArtifactState::Preparing { waiting_for_response: _ } => {
+				ArtifactState::Preparing { .. } => {
 					// The artifact is already being prepared, so we don't need to do anything.
 				},
-				ArtifactState::FailedToProcess(_) => {},
+				ArtifactState::FailedToProcess { last_time_failed, num_failures, error: _ } => {
+					// TODO: Do we want to retry for heads-up requests?
```
Comment (m-cat) [inline node/core/pvf/src/host.rs:602]: Figured we wanted the same logic for heads-up requests, but wanted to double-check.

**Comment by m-cat** [comment]
I figured out how to test this, but I will wait until the general structure of the change is approved.

**Comment by m-cat** [comment]
I had a conversation with @ordian about this change. He was wondering if we should retry for every `PrepareError` or if we could skip on e.g. `Prevalidation` errors, as a retry probably wouldn't fix that. 

I am inclined to keep it simple and not add extra hacks. I think @pepyakin would say something similar, that this is cold code and so the performance for this case doesn't matter too much.

**Comment by slumber** [comment]
> I had a conversation with @ordian about this change. He was wondering if we should retry for every `PrepareError` or if we could skip on e.g. `Prevalidation` errors, as a retry probably wouldn't fix that.
> 
> I am inclined to keep it simple and not add extra hacks. I think @pepyakin would say something similar, that this is cold code and so the performance for this case doesn't matter too much.

I wouldn't expect validators to retry compiling bad code, and I don't see a reason to call it a hack, it is a simple match on an error.

However, if the code is indeed malicious, then we should detect it during prechecking, submit invalid vote and reject it, thus no retries.

If it was prechecked before, no Prevalidation errors should happen. Which is again an external guarantee.

All in all, not so much difference

**Comment by m-cat** [comment]
> I wouldn't expect validators to retry compiling bad code, and I don't see a reason to call it a hack, it is a simple match on an error.

@slumber Fair enough, to me it just felt like a lot of logic for an edge case. But I can add it, with a note explaining that we don't expect to hit that match.

> However, if the code is indeed malicious, then we should detect it during prechecking, submit invalid vote and reject it, thus no retries.

Gotcha. Can you please point me to where this happens in the code?

**Comment by slumber** [comment]
> Gotcha. Can you please point me to where this happens in the code?

When the validation is requested, validator always fetches the code from the Runtime, either by hash or relay parent.
For example,
https://github.com/paritytech/polkadot/blob/e3f67317030ce6358596780370c8d221f3a65191/node/core/candidate-validation/src/lib.rs#L361-L367

In order for the code to get stored in the Runtime storage, it should undergo prechecking process (it's not yet enabled but soon will be), this happens in the paras pallet (on upgrade or initialisation):
https://github.com/paritytech/polkadot/blob/e3f67317030ce6358596780370c8d221f3a65191/runtime/parachains/src/paras/mod.rs#L1770-L1775

File: node/core/pvf/src/artifacts.rs [hunk 2]
```diff
@@ -103,10 +103,22 @@ pub enum ArtifactState {
...
+	},
 	/// The code couldn't be compiled due to an error. Such artifacts
 	/// never reach the executor and stay in the host's memory.
-	FailedToProcess(PrepareError),
+	FailedToProcess {
+		/// Keep track of the last time that processing this artifact failed.
+		last_time_failed: SystemTime,
+		/// The number of times this artifact has failed to prepare.
+		num_failures: u32,
+		/// The prepare error.
```
Comment (pepyakin) [inline node/core/pvf/src/artifacts.rs:119]: Nit: tautology. What is this error exactly? The last one I presume?

File: node/core/pvf/src/host.rs [hunk 3]
```diff
@@ -596,20 +667,26 @@ async fn handle_prepare_done(
...
 			// processed at this point.
 			never!("the artifact is already processed unsuccessfully: {:?}", artifact_id);
 			return Ok(())
 		},
-		Some(state @ ArtifactState::Preparing { waiting_for_response: _ }) => state,
+		Some(state @ ArtifactState::Preparing { .. }) => state,
 	};
 
-	if let ArtifactState::Preparing { waiting_for_response } = state {
+	let num_failures = if let ArtifactState::Preparing { waiting_for_response, num_failures } =
```
Comment (pepyakin) [inline node/core/pvf/src/host.rs:679]: Nit: I wonder if it's time to move it under the match above? Then, `let state` would become `let (state, num_failures)` and/or `waiting_for_response`.

File: node/core/pvf/src/host.rs [hunk 4]
```diff
@@ -446,11 +457,28 @@ async fn handle_precheck_pvf(
...
 				let _ = result_sender.send(Ok(()));
 			},
-			ArtifactState::Preparing { waiting_for_response } =>
+			ArtifactState::Preparing { waiting_for_response, num_failures: _ } =>
 				waiting_for_response.push(result_sender),
-			ArtifactState::FailedToProcess(result) => {
-				let _ = result_sender.send(PrepareResult::Err(result.clone()));
-			},
+			ArtifactState::FailedToProcess { last_time_failed, num_failures, error } =>
+				if can_retry_prepare_after_failure(*last_time_failed, *num_failures) {
```
Comment (eskimor) [inline node/core/pvf/src/host.rs:463]: NIT: For preparation we actually agreed that retrying is not required/desired here. The pre-checking logic will not actually retry anyway, so this code will never get executed - so it is fine, but given that not doing it actually simplifies things, instead of complicating things (due to this complete separate implementation) - I would suggest to just not do it.

Comment (eskimor) [reply node/core/pvf/src/host.rs:463]: Would also remove some code duplication.

**Review by eskimor — COMMENTED** [review]
Nice, great work @m-cat !

**Comment by eskimor** [comment]
@slumber has a good point, but as he also argued: We do not retry during prechecking and after prechecking, malicious code can be ruled out. So I am fine with retrying in any case, especially given that we will only do so every 15 minutes.

File: node/core/pvf/src/host.rs (hunk 3 above)
Comment (m-cat) [reply node/core/pvf/src/host.rs:679]: I gave it a try, but I wasn't able to work around the compiler errors when I do that.

File: node/core/pvf/src/host.rs (hunk 4 above)
Comment (m-cat) [reply node/core/pvf/src/host.rs]: Makes sense, removed.

**Review by slumber — APPROVED** [review]
Don't forget to add tests, please

**Review by eskimor — APPROVED** [review]
Nice work @m-cat !
