### PR TITLE
Remove usage of substrate-test-runtime.

### LINKED ISSUE #946: Test runtime is not useable
The Polkadot test runtime currently can not be used. The main problem is that it includes `Extrinsic` and `GenesisConfig` from `substrate-test-runtime`. This means if we try to send an `Extrinsic` or build the genesis, it will fail.

### PR DESCRIPTION
**Pull request by expenses**
Closes #946.

### CODE REVIEW

**Comment by expenses** [comment]
@bkchr the tests fail with ` thread 'block_import::import_single_good_known_block_is_ignored' panicked at 'called `Result::unwrap()` on an `Err` value: Execution(Wasmi(Trap(Trap { kind: Unreachable })))', network/test/src/block_import.rs:30:17`.
What should I do to debug this?

File: runtime/test-runtime/src/genesismap.rs [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+use sp_io::hashing::{blake2_256, twox_128};
+use super::{AccountId, WASM_BINARY};
+use codec::{Encode, KeyedVec, Joiner};
+use sp_core::{ChangesTrieConfiguration, map};
+use sp_core::storage::{well_known_keys, Storage};
+use sp_runtime::BuildStorage;
+use sp_runtime::traits::{Block as BlockT, Hash as HashT, Header as HeaderT};
+
+/// Configuration of a general Substrate test genesis block.
+pub struct GenesisConfig {
```
Comment (bkchr) [inline runtime/test-runtime/src/genesismap.rs:29]: Why did you copy all this code? You don't need it.

**Comment by bkchr** [comment]
> @bkchr the tests fail with `thread 'block_import::import_single_good_known_block_is_ignored' panicked at 'called`Result::unwrap()`on an`Err` value: Execution(Wasmi(Trap(Trap { kind: Unreachable })))', network/test/src/block_import.rs:30:17`.
> What should I do to debug this?

I don't know what these tests are doing. You probably need to debug them.

**Comment by rphmeier** [comment]
@expenses The test failure is probably related to the stuff we talked about before - that the `Parachains` module expects the `SetHeads` inherent, and the primitives here isn't providing it.

**Comment by bkchr** [comment]
If you set a logger and run with `runtime=trace`, you will see the panic message of the runtime.

File: runtime/test-runtime/client/src/lib.rs [hunk 2]
```diff
@@ -321,3 +316,20 @@ pub fn new_light_fetcher() -> LightFetcher {
...
+pub fn needed_extrinsics() -> (polkadot_test_runtime::UncheckedExtrinsic, polkadot_test_runtime::UncheckedExtrinsic) {
+	use polkadot_runtime_common::parachains;
+
+	let set_heads = polkadot_test_runtime::UncheckedExtrinsic {
+		function: polkadot_test_runtime::Call::Parachains(parachains::Call::set_heads(Vec::new())),
+		signature: None,
+	};
+
+	let timestamp = polkadot_test_runtime::UncheckedExtrinsic {
+		function: polkadot_test_runtime::Call::Timestamp(pallet_timestamp::Call::set(0)),
```
Comment (bkchr) [inline runtime/test-runtime/client/src/lib.rs:330]: You should use the correct timestamp here (milliseconds since UNIX epoch).

File: runtime/test-runtime/client/src/lib.rs [hunk 3]
```diff
@@ -321,3 +316,20 @@ pub fn new_light_fetcher() -> LightFetcher {
 pub fn new_native_executor() -> sc_executor::NativeExecutor<LocalExecutor> {
 	sc_executor::NativeExecutor::new(sc_executor::WasmExecutionMethod::Interpreted, None, 8)
 }
+
+/// Extrinsics that must be included in each block.
+pub fn needed_extrinsics() -> (polkadot_test_runtime::UncheckedExtrinsic, polkadot_test_runtime::UncheckedExtrinsic) {
```
Comment (bkchr) [inline runtime/test-runtime/client/src/lib.rs:321]: I think it would be nice to take the `heads` as parameter.

File: runtime/test-runtime/src/genesismap.rs [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+			.map(|&(ref account, balance)| (account.to_keyed_vec(b"balance:"), vec![].and(&balance)))
+			.map(|(k, v)| (blake2_256(&k[..])[..].to_vec(), v.to_vec()))
+			.chain(vec![
+				(well_known_keys::CODE.into(), wasm_runtime),
+				(
+					well_known_keys::HEAP_PAGES.into(),
+					vec![].and(&(self.heap_pages_override.unwrap_or(16 as u64))),
+				),
+			].into_iter())
+			.collect();
```
Comment (bkchr) [inline runtime/test-runtime/src/genesismap.rs:64]: This code is not needed.

File: runtime/test-runtime/src/genesismap.rs [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+		if let Some(ref changes_trie_config) = self.changes_trie_config {
+			map.insert(well_known_keys::CHANGES_TRIE_CONFIG.to_vec(), changes_trie_config.encode());
+		}
+		// Add the extra storage entries.
+		map.extend(self.extra_storage.top.clone().into_iter());
+
+		// Assimilate the system genesis config.
+		let mut storage = Storage { top: map, children: self.extra_storage.children.clone()};
+		let config = crate::GenesisConfig {
+            system: None,
```
Comment (bkchr) [inline runtime/test-runtime/src/genesismap.rs:74]: We should set `CODE` here in the System genesis config.

File: runtime/test-runtime/client/src/lib.rs (hunk 3 above)
Comment (bkchr) [reply runtime/test-runtime/client/src/lib.rs:321]: And why not just return a `Vec`? If in the future we add another inherent, we would need to touch every line that uses this function.

**Comment by expenses** [comment]
@bkchr this should be ready for review now.

File: runtime/test-runtime/src/genesismap.rs [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+			balances: endowed_accounts.into_iter().map(|a| (a, balance * currency::DOLLARS)).collect(),
+			extra_storage,
+		}
+	}
+
+	pub fn genesis_map(&self) -> Storage {
+		// Assimilate the system genesis config.
+		let mut storage = Storage { top: BTreeMap::new(), children: self.extra_storage.children.clone()};
+		let config = crate::GenesisConfig {
+            system: Some(system::GenesisConfig {
```
Comment (bkchr) [inline runtime/test-runtime/src/genesismap.rs:51]: Spaces.

File: runtime/test-runtime/src/genesismap.rs [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+				changes_trie_config: self.changes_trie_config.clone(),
+				code: WASM_BINARY.to_vec(),
+			}),
+            babe: None,
+            indices: None,
+            balances: Some(balances::GenesisConfig {
+				balances: self.balances.clone()
+			}),
+            staking: None,
```
Comment (bkchr) [inline runtime/test-runtime/src/genesismap.rs:60]: Spaces.

File: service/src/grandpa_support.rs [hunk 8]
```diff
@@ -244,13 +244,21 @@ mod tests {
 
 	#[test]
 	fn grandpa_pause_voting_rule_works() {
+		env_logger::init();
```
Comment (bkchr) [inline service/src/grandpa_support.rs:247]:
```suggestion
		let _ = env_logger::try_init();
```

Never call `init()` in a test.

File: runtime/test-runtime/src/genesismap.rs [hunk 9]
```diff
@@ -0,0 +1,72 @@
+// Copyright 2017-2020 Parity Technologies (UK) Ltd.
```
Comment (bkchr) [inline runtime/test-runtime/src/genesismap.rs:1]:
```suggestion
// Copyright 2020 Parity Technologies (UK) Ltd.
```
