### PR TITLE
Dispute coordinator - Recover disputes on startup

### LINKED ISSUE #3445: Dispute Coordinator should recover started disputes on startup
On startup the dispute coordinator should check the DB for recorded votes for non concluded disputes we have not yet
recorded a local statement for. For all of those send `DisputeParticipationMessage::Participate` message to dispute participation subsystem.

This is to ensure we will properly participate in a dispute even in the case of restarts/crashes.

### PR DESCRIPTION
**Pull request by Lldenaurois**
This PR modifies the dispute coordinator to send a `DisputeCoordinatorMessage::Participate` for each non-concluded dispute for which the subsystem has no local statement on restarts. 

Before entering the main event loop, the subsystem will attempt to resume operation by:
 1. Fetching the set of active leaves by issuing `ChainSelection::Leaves` request.
 2. Reconstructing the rolling session window and session infos by calling `handle_new_activations` for the returned leaves.
 3. Loading the non-concluded disputes and their corresponding candidate votes from the database respectively.
 4. Sending a `DisputeCoordinatorMessage::Participate` for any disputes that are missing a local statement.

Along the way the test harness is also refactored to ergonomically support restarting the subsystem, while carrying over any database state between executions.

Fixes #3445

### CODE REVIEW

File: node/core/dispute-coordinator/src/lib.rs [hunk 1]
```diff
@@ -349,6 +351,103 @@ where
...
+) -> Result<(), Error>
+where
+	Context: overseer::SubsystemContext<Message = DisputeCoordinatorMessage>,
+	Context: SubsystemContext<Message = DisputeCoordinatorMessage>,
+	B: Backend,
+{
+
+	// Query for the set of active leaves to reconstruct our rolling session window.
+	let (tx, rx) = oneshot::channel();
+	ctx.send_message(ChainSelectionMessage::Leaves(tx)).await;
```
Comment (Lldenaurois) [inline node/core/dispute-coordinator/src/lib.rs:374]: Is this the proper way to reconstruct a `RollingSessionWindow`?

That is, should we fetch `Leaves` from the ChainSelection subsystem and subsequently call `handle_new_activations` for all leaves?

File: node/core/dispute-coordinator/src/lib.rs [hunk 2]
```diff
@@ -671,6 +770,9 @@ async fn handle_import_statements(
 
 	overlay_db.write_candidate_votes(session, candidate_hash, votes.into());
 
+	// TODO(ladi): should we respond with ImportStatementsResult::ValidImport?
+	//pending_confirmation.send(ImportStatementsResult::ValidImport) .map_err(|_| Error::OneshotSend)?;
```
Comment (Lldenaurois) [inline node/core/dispute-coordinator/src/lib.rs:774]: Question: We do not reply to the pending confirmation? Is this desired behavior?

In it's current form, handle_new_activations he caller will only ever receive a reply on an invalid import (see above). Should we not also reply with `ValidImport` upon success?

File: node/core/dispute-coordinator/src/lib.rs [hunk 3]
```diff
@@ -349,6 +351,103 @@ where
...
+			ctx.send_message(DisputeParticipationMessage::Participate {
+				candidate_hash: *candidate_hash,
+				candidate_receipt: votes.candidate_receipt.clone(),
+				session,
+				n_validators: n_validators as u32,
+				report_availability,
+			}).await;
+
+			// TODO(ladi): do we care about the response here?
+			let _ = receive_availability.await;
```
Comment (Lldenaurois) [inline node/core/dispute-coordinator/src/lib.rs:444]: Should we handle the responses on the participation message?

**Review by Lldenaurois — COMMENTED** [review]
Additional Question:

Do we need to have any special handling for the dispute availability checks during restart? Or is it safe to ignore dispute availability checks?

File: node/core/dispute-coordinator/src/lib.rs [hunk 4]
```diff
@@ -349,6 +351,103 @@ where
...
+	let mut overlay_db = OverlayedBackend::new(backend);
+	handle_new_activations(ctx, &mut overlay_db, state, leaves).await.unwrap();
+	let write_ops = overlay_db.into_write_ops();
+	backend.write(write_ops)?;
+
+	let recent_disputes = match backend.load_recent_disputes() {
+		Ok(Some(disputes)) => disputes,
+		Ok(None) => return Ok(()),
+		Err(e) => {
+			tracing::error!(target: LOG_TARGET, "failed initial load of recent disputes: {:?}", e);
```
Comment (drahnr) [inline node/core/dispute-coordinator/src/lib.rs:388]:
```suggestion
			tracing::error!(target: LOG_TARGET, "Failed initial load of recent disputes: {:?}", e);
```

File: node/core/dispute-coordinator/src/lib.rs [hunk 5]
```diff
@@ -316,6 +316,8 @@ where
 		rolling_session_window: RollingSessionWindow::new(DISPUTE_WINDOW),
 	};
 
+	resume(ctx, &mut state, backend).await?;
```
Comment (ordian) [inline node/core/dispute-coordinator/src/lib.rs:319]: it should probably be called in `run` outside of the loop

unrelated: the naming of this function `run_iteration` is a bit misleading, it should probably be called `run_until_error` or something like that

File: node/core/dispute-coordinator/src/lib.rs (hunk 3 above)
Comment (drahnr) [reply node/core/dispute-coordinator/src/lib.rs:444]: The response is a `bool`, so the handling should be rather easy and at least add a trace level message. I am not sure if availability is an invariant we want to check at this point or not.

File: node/core/dispute-coordinator/src/lib.rs [hunk 6]
```diff
@@ -349,6 +351,103 @@ where
...
+		};
+
+		let n_validators = validators.len();
+		let voted_indices: HashSet<_> = votes.voted_indices().into_iter().collect();
+		for (index, validator) in validators.iter().enumerate() {
+			let index = ValidatorIndex(index as _);
+			if voted_indices.contains(&index) { continue }
+
+			// Skip non-local validators.
+			if state.keystore.key_pair::<ValidatorPair>(validator).ok().flatten().is_none() {
```
Comment (drahnr) [inline node/core/dispute-coordinator/src/lib.rs:428]:
```suggestion
			if let Ok(None) = state.keystore.key_pair::<ValidatorPair>(validator) {
```

File: node/core/dispute-coordinator/src/lib.rs [hunk 7]
```diff
@@ -349,6 +351,103 @@ where
...
+				continue
+			}
+
+			// Send a DisputeParticipationMessage for all non-concluded disputes that for which
+			// we have not recorded a local statement.
```
Comment (drahnr) [inline node/core/dispute-coordinator/src/lib.rs:433]:
```suggestion
			// Send a `DisputeParticipationMessage` for all non-concluded disputes which
			// do not have a recorded local statement.
```

**Review by drahnr — COMMENTED** [review]
A few nits, generally looks good. The open questions need some more eyes / more dispute knowledgeable eyes.

File: node/core/dispute-coordinator/src/lib.rs (hunk 7 above)
Comment (ordian) [inline node/core/dispute-coordinator/src/lib.rs:433]: I may be lacking understanding of dispute coordinator internals, but where do we check we haven't recorded a local statement?

File: node/core/dispute-coordinator/src/lib.rs (hunk 6 above)
Comment (ordian) [inline node/core/dispute-coordinator/src/lib.rs:428]: this is probably copied from somewhere, but we should use `has_keys` instead of `key_pair.is_none()`

File: node/core/dispute-coordinator/src/lib.rs [hunk 8]
```diff
@@ -349,6 +351,103 @@ where
 	}
 }
 
+// Restores the subsystem's state before proceeding with the main event loop. Primarily, this
+// repopulates the rolling session window the relevant session information to handle incoming
+// import statement requests.
+//
+// This method also retransmits a DisputeParticiationMessage::Participate for any non-concluded
+// disputes for which the subsystem doesn't have a local statement, ensuring it eventually makes an
+// arbitration on the disupte.
```
Comment (ordian) [inline node/core/dispute-coordinator/src/lib.rs:360]:
```suggestion
// arbitration on the dispute.
```

File: node/core/dispute-coordinator/src/lib.rs [hunk 9]
```diff
@@ -349,6 +351,103 @@ where
...
+		Ok(None) => return Ok(()),
+		Err(e) => {
+			tracing::error!(target: LOG_TARGET, "failed initial load of recent disputes: {:?}", e);
+			return Err(e.into());
+		},
+	};
+
+	// Filter out disputes that have already concluded.
+	let active_disputes = recent_disputes.into_iter()
+		.filter(|((_, _), status)| status.concluded_at().is_none())
```
[the remark this answers is not in the document]
Comment (ordian) [reply node/core/dispute-coordinator/src/lib.rs:395]:
```suggestion
		.filter(|(_, status)| status == DisputeStatus::Active)
```

File: node/core/dispute-coordinator/src/lib.rs (hunk 1 above)
Comment (rphmeier) [reply node/core/dispute-coordinator/src/lib.rs:374]: I think we should instead run the `resume` logic on the first time we receive an `ActivatedLeaf` from the overseer. The overseer gives all current leaves on startup. We shouldn't need any dependency on `ChainSelection`

File: node/core/dispute-coordinator/src/lib.rs (hunk 3 above)
Comment (rphmeier) [reply node/core/dispute-coordinator/src/lib.rs:444]: I agree with Bernhard.

I think that we should at least `tracing::debug!` log if there's something which is unavailable, but it's not necessary to check for what we're doing here.

File: node/core/dispute-coordinator/src/lib.rs [hunk 10]
```diff
@@ -349,6 +351,103 @@ where
...
+
+			// Skip non-local validators.
+			if state.keystore.key_pair::<ValidatorPair>(validator).ok().flatten().is_none() {
+				continue
+			}
+
+			// Send a DisputeParticipationMessage for all non-concluded disputes that for which
+			// we have not recorded a local statement.
+			let (report_availability, receive_availability) = oneshot::channel();
+			ctx.send_message(DisputeParticipationMessage::Participate {
```
Comment (rphmeier) [inline node/core/dispute-coordinator/src/lib.rs:435]: Although the comment above indicates that we only do this for disputes we haven't issued local statements for, there doesn't seem to be any check of the `CandidateVotes` to find the `ValidatorIndex`.

Comment (rphmeier) [reply node/core/dispute-coordinator/src/lib.rs:435]: NVM - found it at the top of the loop.

File: node/core/dispute-coordinator/src/lib.rs [hunk 11]
```diff
@@ -349,6 +351,103 @@ where
...
+				candidate_hash: *candidate_hash,
+				candidate_receipt: votes.candidate_receipt.clone(),
+				session,
+				n_validators: n_validators as u32,
+				report_availability,
+			}).await;
+
+			// TODO(ladi): do we care about the response here?
+			let _ = receive_availability.await;
+		}
```
Comment (rphmeier) [inline node/core/dispute-coordinator/src/lib.rs:445]: we should `break` here. There's really no situation where we'll expect to run a node on behalf of multiple validators. After finding the first key we control for the session, we should back off.

File: node/core/dispute-coordinator/src/lib.rs (hunk 2 above)
Comment (rphmeier) [reply node/core/dispute-coordinator/src/lib.rs:774]: Yeah, nice catch. Should be covered in tests as well.

File: node/core/dispute-coordinator/src/lib.rs [hunk 12]
```diff
@@ -349,6 +349,102 @@ where
...
+				session,
+				n_validators: n_validators as u32,
+				report_availability,
+			}).await;
+
+			if !receive_availability.await? {
+				tracing::debug!(target: LOG_TARGET, "Participation failed. Candidate not available");
+			} else {
+				break
+			}
```
Comment (Lldenaurois) [inline node/core/dispute-coordinator/src/lib.rs:441]: @rphmeier @drahnr Is this the desired behavior when handling the receive_availability?

**Comment by Lldenaurois** [comment]
@rphmeier How do we keep track of when we've recovered all Statements for all leaves? In this current setting we simply always handle each leaf as it comes in.

File: node/core/dispute-coordinator/src/lib.rs [hunk 13]
```diff
@@ -349,6 +377,100 @@ where
...
+		// Determine if there are any missing local statements for this dispute. Validators are
+		// filtered if:
+		//  1) their statement already exists, or
+		//  2) the validator key is not in the local keystore (i.e. the validator is remote).
+		// The remaining set only contains local validators that are also missing statements.
+		let missing_local_statement = validators.iter()
+			.enumerate()
+			.map(|(index, validator)| (ValidatorIndex(index as _), validator))
+			.filter(|(index, validator)|
+				voted_indices.contains(index) ||
```
Comment (Lldenaurois) [inline node/core/dispute-coordinator/src/lib.rs:449]: @ordian refactored further. Here is where we check that recorded the local statement.

File: node/core/dispute-coordinator/src/lib.rs [hunk 14]
```diff
@@ -323,12 +341,22 @@ where
...
 			FromOverseer::Signal(OverseerSignal::ActiveLeaves(update)) => {
-				handle_new_activations(
-					ctx,
-					&mut overlay_db,
-					&mut state,
-					update.activated.into_iter().map(|a| a.hash),
-				).await?
+				let leaves = update.activated.into_iter().map(|a| a.hash);
+				if !state.recovery_state.complete() {
+					handle_leaf(
```
Comment (rphmeier) [inline node/core/dispute-coordinator/src/lib.rs:346]: nit: rather than have `handle_leaf` also call `handle_new_activations`, I think it'd be more clear to explicitly invoke it here and rename `handle_leaf` to `handle_startup`

File: node/core/dispute-coordinator/src/lib.rs [hunk 15]
```diff
@@ -71,10 +71,27 @@ const ACTIVE_DURATION_SECS: Timestamp = 180;
 /// Timestamp based on the 1 Jan 1970 UNIX base, which is persistent across node restarts and OS reboots.
 type Timestamp = u64;
 
+#[derive(Eq, PartialEq)]
+enum Recovery {
```
Comment (rphmeier) [inline node/core/dispute-coordinator/src/lib.rs:75]: nit: `Recovery` doesn't seem like the right name, since it's not about recovery but participation on startup.

File: node/core/dispute-coordinator/src/lib.rs [hunk 16]
```diff
@@ -349,6 +377,100 @@ where
...
+		// filtered if:
+		//  1) their statement already exists, or
+		//  2) the validator key is not in the local keystore (i.e. the validator is remote).
+		// The remaining set only contains local validators that are also missing statements.
+		let missing_local_statement = validators.iter()
+			.enumerate()
+			.map(|(index, validator)| (ValidatorIndex(index as _), validator))
+			.filter(|(index, validator)|
+				voted_indices.contains(index) ||
+				state.keystore.key_pair::<ValidatorPair>(validator).map(|v| v.is_none()).unwrap_or_default())
```
Comment (rphmeier) [inline node/core/dispute-coordinator/src/lib.rs:450]:
```suggestion
				state.keystore.key_pair::<ValidatorPair>(validator).map_or(false, |v| v.is_none())
```

`map_or` is more expressive than using `unwrap_or_default` implicitly evaluating to `false` as a default.

File: node/core/dispute-coordinator/src/lib.rs [hunk 17]
```diff
@@ -349,6 +377,100 @@ where
...
+			.count() > 0;
```
Comment (rphmeier) [inline node/core/dispute-coordinator/src/lib.rs:451]: I don't see how this is correct. The iterator contains an entry for each validator which (has voted | has no key). We really want (has not voted & has a key).

Comment (rphmeier) [inline node/core/dispute-coordinator/src/lib.rs:451]:
```suggestion
		let missing_local_statement = validators.iter()
			.enumerate()
			.map(|(index, validator)| (ValidatorIndex(index as _), validator))
			.any(|(index, validator)|
				!voted_indices.contains(index) &&
				state.keystore.key_pair::<ValidatorPair>(validator).ok().flatten().map_or(false, |v| v.is_some())
			);
```

re: https://github.com/paritytech/polkadot/pull/3481/files#r672552299 and https://github.com/paritytech/polkadot/pull/3481/files#r672551425

Comment (rphmeier) [reply node/core/dispute-coordinator/src/lib.rs:451]: > I don't see how this is correct. The iterator contains an entry for each validator which (has voted | has no key). We really want (has not voted & has a key).

> map_or is more expressive than using unwrap_or_default implicitly evaluating to false as a default.

**Review by rphmeier — CHANGES_REQUESTED** [review]
`missing_local_statement` logic seems wrong to me. Other than that it looks fine.

File: node/core/dispute-coordinator/src/lib.rs (hunk 14 above)
Comment (Lldenaurois) [reply node/core/dispute-coordinator/src/lib.rs:346]: Why didn't I think of that!

File: node/core/dispute-coordinator/src/lib.rs (hunk 17 above)
Comment (Lldenaurois) [reply node/core/dispute-coordinator/src/lib.rs]: I will write a test to ensure we can ensure this property.

**Review by rphmeier — APPROVED** [review]

**Comment by rphmeier** [comment]
bot rebase

**Comment by rphmeier** [comment]
@Lldenaurois I triggered the rebase because I wanted to merge, but it seems like you wanted to have another test. Let's block until that's in and then merge

**Review by rphmeier — APPROVED** [review]
