### PR TITLE
Fixed consensus message garbage collection

### LINKED ISSUE #183: Block generation halted
4 (of 4) validator nodes stopped generating blocks around 0330 last night. They were well connected. Restarting node 4 kickstarted block generation. No logs as yet.

### PR DESCRIPTION
**Pull request by arkpar**
* Removed flaky garbage collection based on block import notification and fixed garbage collection logic.
* Added a fix to prevent downloading block that is being imported from consensus.

Fixes #183

### CODE REVIEW

File: substrate/network/src/consensus.rs [hunk 1]
```diff
@@ -322,3 +308,62 @@ impl Consensus {
 		}
 	}
 }
+
+
+#[test]
+fn collects_garbage() {
```
Comment (rphmeier) [inline substrate/network/src/consensus.rs]: can we place this in a submodule?
