### PR TITLE
Use tempdir for tests

### LINKED ISSUE #992: Test for process interruption generates untracked files
After running any of the cli tests, a few directories are created for data.

There is nothing wrong with that but they should be ignored in the Git repository and not marked as untracked files. If we don't do that, someone WILL commit them by mistake one day.

We should use /tmp instead like in substrate (using tempfile).

Related to: https://github.com/paritytech/substrate/issues/4888

### PR DESCRIPTION
**Pull request by pscott**
This PR adds the [tempfile](https://docs.rs/tempfile/3.1.0/tempfile/index.html) crate as a dev-dependency and replaces the hardcoded test directories to temporary directories.

Running tests should no longer leak any unwanted files.

Closes #992

### CODE REVIEW

File: tests/running_the_node_and_interrupt.rs [hunk 1]
```diff
@@ -26,9 +27,11 @@ fn running_the_node_works_and_can_be_interrupted() {
 	use nix::unistd::Pid;
 
 	fn run_command_and_kill(signal: Signal) {
-		let _ = fs::remove_dir_all("interrupt_test");
+		let tmpdir = tempdir().expect("coult not create temp dir");
+		let base_path = tmpdir.path().to_str().expect("path should consist of valid utf8 characters");
+
 		let mut cmd = Command::new(cargo_bin("polkadot"))
-			.args(&["--dev", "-d", "interrupt_test"])
+			.args(&["--dev", "-d", base_path])
```
Comment (bkchr) [inline tests/running_the_node_and_interrupt.rs:34]: If you remove the last parameter here and call `arg` with `tmpdir.path()` you don't need to a string slice above.

File: tests/invalid_order_arguments.rs [hunk 2]
```diff
@@ -16,11 +16,13 @@
...
+use tempfile::tempdir;
 
 #[test]
 #[cfg(unix)]
 fn invalid_order_arguments() {
-	let base_path = "invalid_order_arguments";
+	let tmpdir = tempdir().expect("could not create temp dir");
+	let base_path = tmpdir.path().to_str().expect("path should consist of valid utf8 characters");
 
 	let status = Command::new(cargo_bin("polkadot"))
```
Comment (bkchr) [inline tests/invalid_order_arguments.rs:27]: Same

File: tests/purge_chain_works.rs [hunk 3]
```diff
@@ -25,9 +26,9 @@ fn purge_chain_works() {
 	use nix::sys::signal::{kill, Signal::SIGINT};
 	use nix::unistd::Pid;
 
-	let base_path = "purge_chain_test";
+	let tmpdir = tempdir().expect("could not create temp dir");
+	let base_path = tmpdir.path().to_str().expect("path should consist of valid utf8 characters");
 
-	let _ = fs::remove_dir_all(base_path);
 	let mut cmd = Command::new(cargo_bin("polkadot"))
 		.args(&["--dev", "-d", base_path])
```
Comment (bkchr) [inline tests/purge_chain_works.rs:33]: Same

File: tests/purge_chain_works.rs [hunk 4]
```diff
@@ -43,12 +44,14 @@ fn purge_chain_works() {
 
 	// Purge chain
 	let status = Command::new(cargo_bin("polkadot"))
-		.args(&["purge-chain", "--dev", "-d", base_path, "-y"])
+		.args(&["purge-chain", "--dev", "-d"])
+		.arg(tmpdir.path())
+		.arg( "-y")
```
Comment (bkchr) [inline tests/purge_chain_works.rs:49]:
```suggestion
		.arg("-y")
```
