### PR TITLE
collator-protocol: short-term fixes for connectivity

### LINKED ISSUE #4435: collator-protocol: short-term fixes for connectivity
Currently, collators add validators to the reserved peerset when a collation is ready and only update it on the next collation.
That means that after a validator disconnects a collator, it will still try to connect back, even if it's not in their backing group.

As a short term fix, we could:
1. Issue a connection request (add to the reserved peerset) on every relay parent activation. This will ensure that we change groups on time on the collator side as well as pre-connection. The downside is that everyone will try to occupy a slot now.
2. Increase the collation peer slots to 50 or 100 to counter the negative effects of 1. Currently, parachain teams have that many collators per parachain.
3. Reduce the https://github.com/paritytech/polkadot/blob/c87a220490f88dfee0d5602fd834f4801916b269/node/network/collator-protocol/src/lib.rs#L61 to 6 or 5 seconds.

_Originally posted by @ordian in https://github.com/paritytech/polkadot/issues/4381#issuecomment-983512599_

### PR DESCRIPTION
**Pull request by ordian**
Fixes #4435.

### CODE REVIEW

File: node/network/collator-protocol/src/collator_side/mod.rs [hunk 1]
```diff
@@ -966,8 +942,54 @@ async fn handle_our_view_change(state: &mut State, view: OurView) -> Result<()>
...
+		tracing::debug!(
+			target: LOG_TARGET,
+			?relay_parent,
+			?validators,
+			para_id = ?id,
+			"Connecting to validators.",
+		);
+
+		// Add the current validator group to the reserved peers
+		connect_to_validators(ctx, validators).await;
```
Comment (eskimor) [inline node/network/collator-protocol/src/collator_side/mod.rs:988]: That might cause issues. `new_leaves` is an `Option` at the moment, but that does not really fix the issue: We are not only collating on the very latest leaf. If we get a new leaves update for forks, we will only be able to collate with validators on the fork which had the most recent leaf update (Assuming other forks have different block numbers and thus might have other validators assigned.) 

We could  collect validators of all currently active leaves. Which in turn means we would stay connected to validators on stale forks, until it's block height gets finalized - so it is not perfect either.

What can happen with this implementation is, that collators will not be able to collate on the "right" fork at rotation boundaries sometimes. Considering that rotation boundaries are tough anyways as of now, this should actually be fine for the interim solution this is. ... so disregard.

**Review by eskimor — APPROVED** [review]

**Comment by eskimor** [comment]
Looks good!

File: node/network/collator-protocol/src/collator_side/mod.rs (hunk 1 above)
Comment (ordian) [reply node/network/collator-protocol/src/collator_side/mod.rs:988]: This is a valid concern which I also have considered, but as you pointed out this is an interim solution.

Comment (ordian) [reply node/network/collator-protocol/src/collator_side/mod.rs:988]: > new_leaves is an Option at the moment, but that does not really fix the issue: We are not only collating on the very latest leaf

note that we're using OurView instead of ActiveLeavesUpdate, so `new_leaves` can be a few leaves

File: node/network/collator-protocol/src/collator_side/mod.rs [hunk 2]
```diff
@@ -966,8 +942,54 @@ async fn handle_our_view_change(state: &mut State, view: OurView) -> Result<()>
...
+		};
+
+		// Determine the group on that core.
+		let current_validators =
+			determine_our_validators(ctx, runtime, our_core, num_cores, relay_parent).await?;
+
+		let validators = current_validators.validators;
+		let no_one_is_assigned = validators.is_empty();
+
+		if no_one_is_assigned {
```
[the remark this answers is not in the document]
Comment (ordian) [reply node/network/collator-protocol/src/collator_side/mod.rs:975]: this was a `warn!` previously, I'll add it back, although I don't remember seeing this message ever in the logs

File: node/network/collator-protocol/src/collator_side/mod.rs (hunk 1 above)
Comment (ordian) [reply node/network/collator-protocol/src/collator_side/mod.rs]: 0ad4aeb

**Review by eskimor — APPROVED** [review]

File: node/network/collator-protocol/src/lib.rs [hunk 3]
```diff
@@ -58,7 +58,7 @@ pub struct CollatorEvictionPolicy {
 impl Default for CollatorEvictionPolicy {
 	fn default() -> Self {
 		CollatorEvictionPolicy {
-			inactive_collator: Duration::from_secs(24),
+			inactive_collator: Duration::from_secs(5),
 			undeclared: Duration::from_secs(1),
```
Comment (rphmeier) [inline node/network/collator-protocol/src/lib.rs:62]: See here (re https://github.com/paritytech/polkadot/pull/4640/files#r805223564)

File: node/network/collator-protocol/src/collator_side/mod.rs [hunk 4]
```diff
@@ -967,6 +943,60 @@ async fn handle_our_view_change(state: &mut State, view: OurView) -> Result<()>
...
+		tracing::warn!(target: LOG_TARGET, "No validators assigned to our core.",);
+		return Ok(())
+	}
+	tracing::debug!(
+		target: LOG_TARGET,
+		?validators,
+		para_id = ?id,
+		"Connecting to validators.",
+	);
+	connect_to_validators(ctx, validators).await;
```
[the remark this answers is not in the document]
Comment (rphmeier) [reply node/network/collator-protocol/src/collator_side/mod.rs:999]: See https://github.com/paritytech/polkadot/pull/4640/files#r805223596
