### PR TITLE
paras: fix upgrade restriction signal

### LINKED ISSUE #3971: `UpgradeRestrictionSignal` is one block off
Assume `UpgradeRestrictionSignal` is set. If `UpgradeRestrictionSignal` is unset at the relay-block `B`, then a parablock that signals an upgrade built with the relay-parent `B-1` can be accepted. However, the post-state at `B-1` forbids an upgrade since `UpgradeRestrictionSignal` is set. That means a non-🤠 parachain will not risk upgrading until it builds a parablock at `B` where the upgrade restriction is lifted.

A potential solution is to unset `UpgradeRestrictionSignal` at `on_finalize` not in `on_initialize`.

### PR DESCRIPTION
**Pull request by pepyakin**
Closes #3971

Read the linked issue.

Apart from that, this addresses the concern raised in this [comment] by
just adding a test. I couldn't find a clean way to reconcile a block
number delay with a PVF voting TTL, so I just resorted to rely on the
test. Should be fine for now.

[comment]: https://github.com/paritytech/polkadot/pull/4457#discussion_r770517562

### CODE REVIEW

**Comment by pepyakin** [comment]
Current dependencies on/for this PR:
* master
  * **PR #4581** 
    * **PR #4580** 
      * **PR #4583** 
        * **PR #4603**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

**Review by eskimor — APPROVED** [review]
Honestly I don't see an issue with https://github.com/paritytech/polkadot/issues/3971 ... but I also don't know how we handle such things in general. I assume this is to make things consistent with other code?

File: runtime/parachains/src/configuration.rs [hunk 1]
```diff
@@ -73,12 +73,26 @@ pub struct HostConfiguration<BlockNumber> {
...
+	///
 	/// If PVF pre-checking is enabled this should be greater than the maximum number of blocks
 	/// PVF pre-checking can take. Intuitively, this number should be greater than the duration
 	/// specified by [`pvf_voting_ttl`]. Unlike, [`pvf_voting_ttl`], this parameter uses blocks
 	/// as a unit.
 	pub validation_upgrade_frequency: BlockNumber,
 	/// The delay, in blocks, before a validation upgrade is applied.
+	///
+	/// The delay is counted from the relay-parent of the candidate that signalled the upgrade. The
+	/// sum of that block and the this delay is dubbed `expected_at`. The first parachain block with
```
[the remark this answers is not in the document]
Comment (pepyakin) [reply runtime/parachains/src/configuration.rs]: Oops. I removed this comment and the comments will be updated with another PR )

File: runtime/parachains/src/paras.rs [hunk 2]
```diff
@@ -1004,7 +1004,9 @@ impl<T: Config> Pallet<T> {
 	}
 
 	/// Called by the initializer to finalize the configuration pallet.
```
Comment (bkchr) [inline runtime/parachains/src/paras.rs:1006]: Not your fault, but the comment is c&p?

**Review by bkchr — APPROVED** [review]

File: runtime/parachains/src/paras.rs (hunk 2 above)
Comment (pepyakin) [reply runtime/parachains/src/paras.rs:1006]: yeah, but it does look correct, or?

Comment (bkchr) [reply runtime/parachains/src/paras.rs:1006]: Is this the configuration pallet?

Comment (pepyakin) [reply runtime/parachains/src/paras.rs:1006]: ah gotcha xD will fix

Comment (pepyakin) [reply runtime/parachains/src/paras.rs:1006]: https://github.com/paritytech/polkadot/pull/4646

**Comment by pepyakin** [comment]
It is not critical by any means, but it is an issue, I believe. Fixing it will actually simplify the behavior from my perspective (at the cost of small complication because of having to do logic in on_finalize) and that will less likely shoot us in the foot down the road

**Comment by pepyakin** [comment]
bot merge
