### PR TITLE
Fix build script for the builder image

### LINKED ISSUE #4743: Fix Docker build script
https://github.com/paritytech/polkadot/blob/cff29a327ab67092c621019da46b136af25ec6fc/scripts/dockerfiles/polkadot/build.sh#L11

The regexp for the version should be:
```
VERSION=`grep "^version" ./cli/Cargo.toml | egrep -o "([0-9\.]+-?[0-9]+)"
```
to cope with `...-N` versions.

Also we can remove the `docker tag` line and 
directly tag both in the `docker build` command with a secon `-t`.

### PR DESCRIPTION
**Pull request by chevdor**
Allows handling versions with dash such as `v1.2.3-1`.

fix #4743

### CODE REVIEW

File: scripts/dockerfiles/polkadot/build.sh [hunk 1]
```diff
@@ -8,17 +8,20 @@ PROJECT_ROOT=`git rev-parse --show-toplevel`
 cd $PROJECT_ROOT
 
 # Find the current version from Cargo.toml
-VERSION=`grep "^version" ./cli/Cargo.toml | egrep -o "([0-9\.]+)"`
+VERSION=`grep "^version" ./cli/Cargo.toml | egrep -o "([0-9\.]+-?[0-9]+)"`
```
Comment (coderobe) [inline scripts/dockerfiles/polkadot/build.sh:11]: i would do something like this instead:
```suggestion
VERSION=`grep "^version" ./cli/Cargo.toml | egrep -o "([0-9\.-]+)"`
```

Comment (chevdor) [reply scripts/dockerfiles/polkadot/build.sh:11]: Why that ? Do you expect some `0.9-1.13` versions or something looking like that ?

Comment (coderobe) [reply scripts/dockerfiles/polkadot/build.sh:11]: 🤷‍♀️  Not necessarily, but shorter regexes are nicer for maintainability IMO.
Fine with either, really

**Review by coderobe — APPROVED** [review]
