### PR TITLE
Reset peers.json if the content is not loadable

### LINKED ISSUE #404: Failed to open peer storage
This issue is more to document the problem and the solution. I don´t think a fix is worth it.
Feel free to comment/close the issue once read.
CC @gavofyork (I think you changed things on the topic recently).

<details>
  <summary>Details</summary>

nodes.json new format:
```
{"QmRMGcQh69t8a8YwzHkofVo9SFr7ffggUwhAYjVSTChmrd":{"addrs":[["/ip4/104.211.54.233/tcp/30333",3155132328031937]]},"QmSz8qCADMmi92QB8dTqMPu56JYQQKZBAHz7y8KXjvqcvW":{"addrs":[["/ip4/40.117.153.33/tcp/30333",3155132328031937]]},"QmWCnXrhM1in1qPqVT3rDXQEJHedAzbPDMimdjqy2P9fGn":{"addrs":[["/ip4/104.211.48.51/tcp/30333",3155132328031937]]},"QmWzYU5X1NpFrprD1YZF5Lcj9aE5WF4QEg5FpvQx5XGWG7":{"addrs":[["/ip4/40.114.120.164/tcp/30333",3155132328031937]]},"QmYPx99i3H8EKXrvYHTBwqz3jjFC1kBfkvmSKd2h9zwQFr":{"addrs":[["/ip4/104.211.48.247/
```

Older format:
```{
  "nodes": [
    {
      "url": "enode://690f4c344d25273eba0fa95463be214cf7c1720120cdad32d46a52483441107167720cd53b072240649d3ae6a6a42969871df983e14b7ec3327acc94195aeb23@10.5.0.184:30300",
      "last_contact": {
        "failure": 1531810202
      }
    },
    {
      "url": "enode://373ad6196df2322a931e396642c38932c85e8f481e4e3bfbff63f20700a67c17a4a700f3e101ef151e3de2bd5da647719619fdbb5820b4fc39aec7f1414ec46c@188.15.33.41:30303",
      "last_contact": {
        "failure": 1531810202
      }
    },
    ...
```

</details>

When a node starts and `nodes.json` contains old data, it reports `Failed to open peer storage` and say the peer data will not be saved.

Either we do a fix that wipes the old file and move on, or we document that users need to delete the file (which I kinda do in this issue :))

### PR DESCRIPTION
**Pull request by chevdor**
Fix #404

Tested manually the following cases:
- no `peers.json`
- incorrect (old format) content in `peers.json`
- correct/current content 
- invalid json in `peers.json`

### CODE REVIEW

**Comment by tomaka** [comment]
I don't think that this is the right fix.
I think we should just ignore the current content of the file if it happens to be invalid, and write over it when we flush.

**Comment by gavofyork** [comment]
disagree. the corollary to "fail fast" is "fix fast". if you spot an invalid/old/stale config file, you should remove it immediately, not rely on a side-effect (i.e. overwriting) later.

File: substrate/network-libp2p/src/network_state.rs [hunk 1]
```diff
@@ -180,8 +181,21 @@ impl NetworkState {
 				PeersStorage::Json(peerstore)
 			} else {
 				warn!(target: "sub-libp2p", "Failed to open peer storage {:?} \
-					; peers won't be saved", path);
-				PeersStorage::Memory(MemoryPeerstore::empty())
+					; peers file will be reset", path);
+				fs::remove_file(&path).unwrap();
+				while Path::new(&path).exists() {
```
Comment (gavofyork) [inline substrate/network-libp2p/src/network_state.rs]: is this loop really necessary?

Comment (chevdor) [reply substrate/network-libp2p/src/network_state.rs]: `fs::remove_file` may, or not, be performed synchronously, this seems to be OS dependant. On my machine (OSX), this loop is useless. It may not be the case for other systems.

File: substrate/network-libp2p/src/network_state.rs [hunk 2]
```diff
@@ -180,8 +181,21 @@ impl NetworkState {
 				PeersStorage::Json(peerstore)
 			} else {
 				warn!(target: "sub-libp2p", "Failed to open peer storage {:?} \
-					; peers won't be saved", path);
-				PeersStorage::Memory(MemoryPeerstore::empty())
+					; peers file will be reset", path);
+				fs::remove_file(&path).unwrap();
```
Comment (rphmeier) [inline substrate/network-libp2p/src/network_state.rs]: codebase style is to use `expect` and prove that the unwrap will not trigger

Comment (rphmeier) [reply substrate/network-libp2p/src/network_state.rs]: (in this case, I'm not sure that can be proven. you should try to handle the error somehow, maybe by logging it)

Comment (chevdor) [reply substrate/network-libp2p/src/network_state.rs]: ok I will adjust

File: substrate/network-libp2p/src/network_state.rs (hunk 1 above)
Comment (tomaka) [reply substrate/network-libp2p/src/network_state.rs]: I'm a bit afraid that this will deadlock if the user's system decides to do some black magic, but maybe I'm not rational.

Comment (chevdor) [reply substrate/network-libp2p/src/network_state.rs]: I find that paranoically-healthy @tomaka :)

I guess I could add some sort of timeout. I am not sure which OS we target but an option is also to check that it works for OSX, Linux and Windows and remove the loop entirely.

Your take on that one, just tell me.

File: substrate/network-libp2p/src/network_state.rs [hunk 3]
```diff
@@ -175,17 +176,35 @@ impl NetworkState {
...
+					if !Path::new(&path).exists() {
+						break;
+					} else {
+						debug!("Waiting for effective deletion of invalid/outdate peers.json");
+						thread::sleep(time::Duration::from_millis(5));
+					}
+				}
+
+				if let Ok(peerstore) = JsonPeerstore::new(path.clone()) {
+					debug!("peers.json reset");
```
Comment (tomaka) [inline substrate/network-libp2p/src/network_state.rs]: Note that this also happens if the file doesn't exist in the first place, ie. if the user starts polkadot for the first time, so the message is not totally correct.

File: substrate/network-libp2p/src/network_state.rs [hunk 4]
```diff
@@ -175,17 +176,35 @@ impl NetworkState {
...
+					NodeStore::Json(peerstore)
+				} else {
+					warn!(target: "sub-libp2p",
+						"Failed to reset peer storage {:?}; peers change will not be saved",
```
Comment (tomaka) [inline substrate/network-libp2p/src/network_state.rs]: This can also happen if the user doesn't have the permission to open the file, so the message should just be `Failed to open peer storage` IMO.

File: substrate/network-libp2p/src/network_state.rs (hunk 3 above)
Comment (chevdor) [reply substrate/network-libp2p/src/network_state.rs]: If the file does not exist in the first place, the first test L179 will kick in and the message you mention L196 will never show up.

File: substrate/network-libp2p/src/network_state.rs (hunk 4 above)
Comment (chevdor) [reply substrate/network-libp2p/src/network_state.rs]: Would not the message L182 already say that?
I can change the message, no problem. We would then have 2 identical messages. Would you prefer that?

If the file cannot be open because of permissions, this should be caught by the first tests. The message `Failed to reset peer storage` really comes second, only after we tried deleting and recreating the file.
