### PR TITLE
Dispute-coordinator: fix underflow panic

### LINKED ISSUE #4554: Node panic at startup
Hi, I'm reviewing errors in `zombienet` and found that nodes spawned (from master) are `panic`  with the following backtrace

```
Version: 0.9.13-63b5907d-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:628:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:519:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
   4: rust_begin_unwind
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   5: core::panicking::panic_fmt
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   6: core::panicking::panic
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: polkadot_node_core_dispute_coordinator::real::DisputeCoordinatorSubsystem::initialize::{{closure}}
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: std::panicking::try
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  14: tokio::runtime::task::core::CoreStage<T>::poll
  15: tokio::runtime::task::harness::Harness<T,S>::poll
  16: std::thread::local::LocalKey<T>::with
  17: tokio::runtime::thread_pool::worker::Context::run_task
  18: tokio::runtime::thread_pool::worker::Context::run
  19: tokio::macros::scoped_tls::ScopedKey<T>::set
  20: tokio::runtime::thread_pool::worker::run
  21: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  22: std::panicking::try
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::blocking::pool::Inner::run
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
  28: start_thread
  29: clone

Thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', /builds/parity/polkadot/node/core/dispute-coordinator/src/real/ordering/mod.rs:282
```

I can reproduce locally and in the gcp cluster if you need access to review, also you can see the logs of the nodes in grafana

https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%221639744688327%22,%221639766288327%22,%22loki.parity-zombienet%22,%7B%22expr%22:%22%7Bpod%3D~%5C%22zombie-a917e907347bf07b79bd6348784d7d82%2Falice%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D

Thanks!

UPDATE: This only happens to `validator` nodes, `full-node`s works as expected.

https://grafana.parity-mgmt.parity.io/explore?orgId=1&left=%5B%221639744688327%22,%221639766288327%22,%22loki.parity-zombienet%22,%7B%22expr%22:%22%7Bpod%3D~%5C%22zombie-a917e907347bf07b79bd6348784d7d82%2Fbootnode%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true%7D%5D

### PR DESCRIPTION
**Pull request by slumber**
Resolves #4554 

skip check-dependent-cumulus

### CODE REVIEW

File: node/core/dispute-coordinator/src/real/ordering/tests.rs [hunk 1]
```diff
@@ -197,7 +201,16 @@ async fn assert_block_ancestors_request(virtual_overseer: &mut VirtualOverseer,
 		AllMessages::ChainApi(ChainApiMessage::Ancestors { hash, k, response_channel }) => {
 			let maybe_block_position = chain.iter().position(|h| *h == hash);
 			let ancestors = maybe_block_position
-				.map(|idx| chain[..idx].iter().rev().take(k).copied().collect())
+				.map(|idx| {
+					if idx == 0 {
+						// Return zero hash for the genesis block -- the same way
+						// Chain API does.
+						vec![Hash::zero()]
```
Comment (drahnr) [inline node/core/dispute-coordinator/src/real/ordering/tests.rs:208]: I am not convinced that this is sane. What would we ever do withthe zero hash? The genesis should not return ancestors, not a garbage one.

File: node/core/dispute-coordinator/src/real/ordering/mod.rs [hunk 2]
```diff
@@ -295,12 +295,13 @@ impl OrderingProvider {
 
 				ancestors.push(*hash);
 			}
+
 			match hashes.last() {
-				Some(last_hash) => {
+				Some(last_hash) if !block_numbers.is_empty() => {
```
Comment (eskimor) [inline node/core/dispute-coordinator/src/real/ordering/mod.rs:300]: I would find hashes.len() more intuitive here and would also help avoid the clone above.

File: node/core/dispute-coordinator/src/real/ordering/tests.rs (hunk 1 above)
Comment (eskimor) [reply node/core/dispute-coordinator/src/real/ordering/tests.rs:208]: I agree, although a check that we won't ever underflow at genesis is not a bad idea.

**Review by eskimor — COMMENTED** [review]
Maybe remove the comment with regards to chain api (we should fix it), but instead add a comment check we are not underflowing at genesis, no matter what.

File: node/core/dispute-coordinator/src/real/ordering/mod.rs (hunk 2 above)
Comment (slumber) [reply node/core/dispute-coordinator/src/real/ordering/mod.rs:300]: Cloning is the same as copying two integers.
The idea of the check is that while `hashes` is not empty, saturating sub could produce empty block numbers range and we don't want to go further (since, well, we don't have block numbers).

Anyway, needs to be reworked together with chain api

Comment (eskimor) [reply node/core/dispute-coordinator/src/real/ordering/mod.rs:300]: fair point!

**Comment by ordian** [comment]
is this obsolete by fixing the chain-api instead?

**Comment by slumber** [comment]
> is this obsolete by fixing the chain-api instead?

It's a good thing to check for underflow anyway, also could use this branch to add some early returns when looking for ancestors is not necessary.

File: node/core/dispute-coordinator/src/real/ordering/mod.rs [hunk 3]
```diff
@@ -279,7 +279,20 @@ impl OrderingProvider {
...
+					// more than N ancestors for block number N.
+					tracing::error!(
+						target: LOG_TARGET,
+						"Received {} ancestors for block number {} from Chain API",
+						hashes.len(),
+						head_number,
+					);
+					return Ok(ancestors)
+				},
+			};
```
Comment (slumber) [inline node/core/dispute-coordinator/src/real/ordering/mod.rs:295]: Doing `saturated_sub` is bad since we will have invalid block number for the next iteration in case of underflow, so it's best to assume this is unreachable.

File: node/core/dispute-coordinator/src/real/ordering/mod.rs [hunk 4]
```diff
@@ -279,7 +279,20 @@ impl OrderingProvider {
...
+					// It's assumed that it's impossible to retrieve
+					// more than N ancestors for block number N.
+					tracing::error!(
+						target: LOG_TARGET,
+						"Received {} ancestors for block number {} from Chain API",
+						hashes.len(),
+						head_number,
+					);
+					return Ok(ancestors)
+				},
```
Comment (eskimor) [inline node/core/dispute-coordinator/src/real/ordering/mod.rs:294]: It is a bit weird to return `Ok` for an error in a function returning `Result`.

Comment (slumber) [reply node/core/dispute-coordinator/src/real/ordering/mod.rs:294]: This branch is considered to be unreachable, so we log this at `error` level and return valid ancestors that we managed to fetch.
It does feel weird but still better than introducing an error variant for the match arm that can only happen in case of a bug in chain API

Comment (eskimor) [reply node/core/dispute-coordinator/src/real/ordering/mod.rs:294]: We actually have a quite a lot of those (errors that should actually be unreachable), but you have a point.

**Comment by eskimor** [comment]
bot merge

**Review by drahnr — APPROVED** [review]

**Comment by drahnr** [comment]
bot merge
