### PR TITLE
Retry failed PVF execution (AmbiguousWorkerDeath)

### LINKED ISSUE #6195: Retry failed PVF execution
PVF execution that fails due to `AmbiguousWorkerDeath` should be retried once. This should reduce the occurrence of failures due to transient conditions.

This can be a good first step towards fully implementing https://github.com/paritytech/polkadot/issues/6102. (Based on recent conversations, it is unclear if we want that. But implementing this present issue would be useful regardless.)

### PR DESCRIPTION
**Pull request by m-cat**
# PULL REQUEST

## Overview

PVF execution that fails due to AmbiguousWorkerDeath should be retried once. This should reduce the occurrence of failures due to transient conditions.

### TODO

- [x] Will write tests once the general structure is approved.

## Issues closed

Closes #6195

### CODE REVIEW

File: node/core/candidate-validation/src/lib.rs [hunk 1]
```diff
@@ -621,28 +625,21 @@ impl ValidationBackend for ValidationHost {
...
-				"cannot send pvf to the validation host: {:?}",
-				err
-			)))
-		}
+		let pvf = Pvf::from_code(raw_validation_code);
 
-		let validation_result = rx
-			.await
-			.map_err(|_| ValidationError::InternalError("validation was cancelled".into()))?;
+		let validation_result = execute_pvf_once(self, pvf.clone(), timeout, params.encode()).await;
```
Comment (s0me0ne-unkn0wn) [inline node/core/candidate-validation/src/lib.rs:630]: Nit: `params` in their encoded form may be used twice so probably it would be better to encode them once into a variable and use it twice, rather than encoding them twice? I mean cloning the already encoded form is cheaper than encoding the source two times.

File: node/core/candidate-validation/src/lib.rs [hunk 2]
```diff
@@ -657,6 +654,27 @@ impl ValidationBackend for ValidationHost {
 	}
 }
 
+// Tries executing a PVF a single time (no retries).
+async fn execute_pvf_once(
```
Comment (s0me0ne-unkn0wn) [inline node/core/candidate-validation/src/lib.rs:658]: Doesn't this fn look like a good candidate for inclusion into `ValidationHost` implementation (not into `ValidationBackend` trait though)?

Comment (slumber) [inline node/core/candidate-validation/src/lib.rs:658]: I propose to keep this code in `validate_candidate` (don't touch it basically) and introduce a new method to `ValidationBackend` trait
```rust
async fn validate_candidate_with_retry(
    ..,
    can_retry: impl Fn(ValidationError) -> bool
)
```
And give it a default implementation (the one you already have) which calls `validate_candidate`

This would make a code easily testable

**Review by slumber — COMMENTED** [review]
Well done, consider a small refactoring

File: node/core/candidate-validation/src/lib.rs (hunk 1 above)
Comment (slumber) [reply node/core/candidate-validation/src/lib.rs:630]: Given there's a 1 second delay, IMO this won't make a difference

Comment (m-cat) [reply node/core/candidate-validation/src/lib.rs:630]: Nice catch. I thought about this; so I expect the retry case to be pretty rare. I would rather encode a second time in the retry case, than unconditionally clone and make an extra heap allocation in every case.

File: node/core/candidate-validation/src/lib.rs (hunk 2 above)
Comment (m-cat) [reply node/core/candidate-validation/src/lib.rs]: Done, except without the `can_retry` parameter as I didn't see a need for it. It would make the code more general but isn't it unnecessary abstraction?

Comment (m-cat) [reply node/core/candidate-validation/src/lib.rs]: Why `ValidationHost`? I think I agree with Chris that it should be in `ValidationBackend` as `ValidationHost` already has `execute_pvf`. However, we need to do some extra stuff around calling `execute_pvf`.

Comment (slumber) [reply node/core/candidate-validation/src/lib.rs]: Whatever you prefer, it was an insignificant suggestion :)

**Review by slumber — APPROVED** [review]
Neat, thanks!

File: node/core/candidate-validation/src/lib.rs [hunk 3]
```diff
@@ -490,7 +496,7 @@ where
 }
 
 async fn validate_candidate_exhaustive(
-	mut validation_backend: impl ValidationBackend,
+	mut validation_backend: impl ValidationBackend + Send,
```
Comment (m-cat) [inline node/core/candidate-validation/src/lib.rs:499]: Suddenly needed this due to the new default implementation of `validate_candidate_with_retry` on the trait. I feel like this bound shouldn't be there, but looks like it gets introduced by the `#[async_trait]` proc macro.

Comment (ordian) [reply node/core/candidate-validation/src/lib.rs:499]: Not sure it's helpful here, but there's a `#[async_trait(?Send)]` variant for that attribute.

File: node/core/candidate-validation/src/lib.rs [hunk 4]
```diff
@@ -60,6 +60,12 @@ mod tests;
 
 const LOG_TARGET: &'static str = "parachain::candidate-validation";
 
+/// The amount of time to wait before retrying after an AmbiguousWorkerDeath validation error.
+#[cfg(not(test))]
+const PVF_EXECUTION_RETRY_DELAY: Duration = Duration::from_secs(1);
```
Comment (ordian) [inline node/core/candidate-validation/src/lib.rs:65]: We use 3 secs delay for spawning workers on failure. I don't think there's exact science behind this number, but at least it's more consistent this way:
```suggestion
const PVF_EXECUTION_RETRY_DELAY: Duration = Duration::from_secs(3);
```

**Review by ordian — APPROVED** [review]

**Review by eskimor — APPROVED** [review]
Nice!

File: node/core/candidate-validation/src/lib.rs (hunk 4 above)
Comment (eskimor) [reply node/core/candidate-validation/src/lib.rs:65]: I don't have a strong opinion, both values have trade-offs. Higher value: More likely transient condition is over already, lower value: More likely we can do the validation in a timely manner.

Comment (ordian) [reply node/core/candidate-validation/src/lib.rs:65]: > > More likely we can do the validation in a timely manner.

You mean for approval-voting specifically (no-shows)? Yes, this is the only case, but it's better be a know-show than to initiate a dispute wrongly.
